# Generated by Django 5.2.8 on 2025-11-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterymeasurement',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
