# Generated by Django 5.2.8 on 2025-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_rename_temprature_batterymeasurement_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterymeasurement',
            name='battery_id',
            field=models.CharField(default='BAT001', max_length=20),
        ),
    ]
