# Generated by Django 6.0.3 on 2026-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0003_batterymeasurement_battery_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batterymeasurement',
            options={'ordering': ['battery_id', 'cycle']},
        ),
        migrations.RemoveField(
            model_name='batterymeasurement',
            name='current',
        ),
        migrations.RemoveField(
            model_name='batterymeasurement',
            name='voltage',
        ),
        migrations.AddField(
            model_name='batterymeasurement',
            name='ica_area_abs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterymeasurement',
            name='ica_peak1_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterymeasurement',
            name='ica_peak1_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterymeasurement',
            name='ica_peak2_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterymeasurement',
            name='ica_peak2_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterymeasurement',
            name='r0_ohm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterymeasurement',
            name='battery_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='batterymeasurement',
            name='capacity',
            field=models.FloatField(help_text='capacity in mAh'),
        ),
        migrations.AlterField(
            model_name='batterymeasurement',
            name='cycle',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='batterymeasurement',
            name='temperature',
            field=models.FloatField(help_text='Tmax_C'),
        ),
        migrations.AlterField(
            model_name='batterymeasurement',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='batterymeasurement',
            constraint=models.UniqueConstraint(fields=('battery_id', 'cycle'), name='uniq_battery_cycle'),
        ),
    ]
